#!/bin/bash
set -e

if [ -f /usr/bin/torii ]; then
  chmod +x /usr/bin/torii
fi

mkdir -p /var/lib/torii
chown torii:torii /var/lib/torii

mkdir -p /etc/torii
chown torii:torii /etc/torii
chmod 0644 /etc/torii/config.yaml

systemctl daemon-reload
systemctl enable torii
systemctl start torii