CREATE TABLE USERS
(
    ID                  INTEGER PRIMARY KEY AUTOINCREMENT,
    USERNAME            VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD            VARCHAR(255) NOT NULL,
    IS_FIRST_TIME_LOGIN BOOL      DEFAULT TRUE,
    ACTIVE              BOOL      DEFAULT FALSE,
    CREATED_AT          TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE SYSTEM_CONFIGURATION
(
    ID                        INTEGER PRIMARY KEY,
    FIRST_TIME_SETUP_COMPLETE BOOLEAN DEFAULT FALSE
);

CREATE TABLE PROXY_METRICS
(
    ID                   INTEGER PRIMARY KEY AUTOINCREMENT,
    REQUEST_COUNT        INTEGER   DEFAULT 0,
    ERROR_COUNT          INTEGER   DEFAULT 0,
    TOTAL_LATENCY_MS     BIGINT    DEFAULT 0,
    AVG_RESPONSE_TIME_MS INTEGER   DEFAULT 0,
    UPSTREAM_TIMEOUTS    INTEGER   DEFAULT 0,
    BYTES_SENT           BIGINT    DEFAULT 0,
    BYTES_RECEIVED       BIGINT    DEFAULT 0,
    ACTIVE_CONNECTIONS   INTEGER   DEFAULT 0,
    REQUEST_2XX_COUNT    INTEGER   DEFAULT 0,
    REQUEST_3XX_COUNT    INTEGER   DEFAULT 0,
    REQUEST_4XX_COUNT    INTEGER   DEFAULT 0,
    REQUEST_5XX_COUNT    INTEGER   DEFAULT 0,
    CACHE_HITS           INTEGER   DEFAULT 0,
    CACHE_MISSES         INTEGER   DEFAULT 0,
    SSL_HANDSHAKES       INTEGER   DEFAULT 0,
    BACKEND_ERRORS       INTEGER   DEFAULT 0,
    UPDATED_AT           TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


INSERT INTO SYSTEM_CONFIGURATION (ID)
VALUES (1);

INSERT INTO PROXY_METRICS (ID) VALUES (1);

INSERT INTO USERS (USERNAME, IS_FIRST_TIME_LOGIN, ACTIVE)
VALUES ('admin', TRUE, TRUE);