CREATE TABLE USER
(
    ID                  INTEGER PRIMARY KEY AUTOINCREMENT,
    USERNAME            VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD            VARCHAR(255) DEFAULT "",
    IS_FIRST_TIME_LOGIN BOOL         DEFAULT TRUE,
    ACTIVE              BOOL         DEFAULT FALSE,
    CREATED_AT          TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT          TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE API_KEY
(
    ID         INTEGER PRIMARY KEY AUTOINCREMENT,
    ALIAS      VARCHAR(255) NOT NULL UNIQUE,
    KEY        VARCHAR(255) NOT NULL UNIQUE,
    SCOPES     TEXT         NOT NULL DEFAULT '',
    EXPIRES_AT TIMESTAMP,
    CREATED_AT TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE ROLE
(
    ID   INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE USER_ROLE
(
    ID      INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID INTEGER NOT NULL,
    ROLE_ID INTEGER NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USER (ID) ON DELETE CASCADE,
    FOREIGN KEY (ROLE_ID) REFERENCES ROLE (ID) ON DELETE CASCADE,
    UNIQUE (USER_ID, ROLE_ID)
);

CREATE TABLE SYSTEM_CONFIGURATION
(
    ID                        INTEGER PRIMARY KEY,
    FIRST_TIME_SETUP_COMPLETE BOOLEAN DEFAULT FALSE
);

CREATE TABLE GLOBAL_PROXY_METRIC
(
    ID                   INTEGER PRIMARY KEY AUTOINCREMENT,
    REQUEST_COUNT        INTEGER   DEFAULT 0,
    ERROR_COUNT          INTEGER   DEFAULT 0,
    TOTAL_LATENCY_MS     BIGINT    DEFAULT 0,
    AVG_RESPONSE_TIME_MS INTEGER   DEFAULT 0,
    UPSTREAM_TIMEOUTS    INTEGER   DEFAULT 0,
    BYTES_SENT           BIGINT    DEFAULT 0,
    BYTES_RECEIVED       BIGINT    DEFAULT 0,
    ACTIVE_CONNECTIONS   INTEGER   DEFAULT 0,
    REQUEST_2XX_COUNT    INTEGER   DEFAULT 0,
    REQUEST_3XX_COUNT    INTEGER   DEFAULT 0,
    REQUEST_4XX_COUNT    INTEGER   DEFAULT 0,
    REQUEST_5XX_COUNT    INTEGER   DEFAULT 0,
    CACHE_HITS           INTEGER   DEFAULT 0,
    CACHE_MISSES         INTEGER   DEFAULT 0,
    SSL_HANDSHAKES       INTEGER   DEFAULT 0,
    BACKEND_ERRORS       INTEGER   DEFAULT 0,
    UPDATED_AT           TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE SESSIONS
(
    TOKEN  TEXT PRIMARY KEY,
    DATA   BLOB NOT NULL,
    EXPIRY REAL NOT NULL
);


CREATE TABLE ACME_ACCOUNT
(
    ID           INTEGER PRIMARY KEY,
    EMAIL        TEXT NOT NULL,
    PRIVATE_KEY  BLOB NOT NULL,
    REGISTRATION TEXT NOT NULL DEFAULT '',
    CREATED_AT   TIMESTAMP     DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ACME_CERTIFICATE
(
    ID                 INTEGER PRIMARY KEY AUTOINCREMENT,
    DOMAIN             TEXT      NOT NULL UNIQUE,
    CERTIFICATE        BLOB      NOT NULL,
    PRIVATE_KEY        BLOB      NOT NULL,
    ISSUER_CERTIFICATE BLOB,
    EXPIRES_AT         TIMESTAMP NOT NULL,
    CREATED_AT         TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT         TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ACME_CONFIGURATION
(
    ID                             INTEGER PRIMARY KEY,
    EMAIL                          TEXT    NOT NULL,
    DNS_PROVIDER                   TEXT    NOT NULL,
    DNS_PROVIDER_SERIALIZED_FIELDS BLOB,
    CA_DIR_URL                     TEXT    NOT NULL DEFAULT '',
    RENEWAL_CHECK_INTERVAL         TEXT    NOT NULL DEFAULT '12h',
    ENABLED                        BOOLEAN NOT NULL DEFAULT TRUE,
    CREATED_AT                     TIMESTAMP        DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT                     TIMESTAMP        DEFAULT CURRENT_TIMESTAMP
);


INSERT INTO SYSTEM_CONFIGURATION (ID)
VALUES (1);

INSERT INTO GLOBAL_PROXY_METRIC (ID)
VALUES (1);

INSERT INTO USER (USERNAME, IS_FIRST_TIME_LOGIN, ACTIVE)
VALUES ('admin', TRUE, TRUE);